Bump version to `0.17.3` and source from GitHub tarball
conda-forge/wandb-feedstock pull request #105
Opened 2024-07-03 17:25 UTC by flferretti

#104 is failing as WandB is not publishing source distributions anymore on PyPI. 

Closes #103

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-07-07 15:29 UTC, Jn58 commented
I've submitted a new PR that builds successfully with version v0.17.4. Please check PR #106  for the details.

2024-07-15 07:52 UTC, flferretti commented
@conda-forge/wandb do you have any update on this? Thanks a lot!

2024-07-23 15:09 UTC, flferretti commented
@conda-forge/core the team seems to be inactive. I've opened #110 to be added as an additional maintainer, but in the meanwhile, this PR and the #108 need to be merged. Thanks a lot for your help!

FYI @ackphill

2024-07-23 15:20 UTC, synapticarbors commented
@flferretti -- Just to note, I've been reviewing #108 and it isn't ready to merge.

2024-07-23 15:21 UTC, flferretti commented
> @flferretti -- Just to note, I've been reviewing #108 and it isn't ready to merge.

Alright, thanks a lot! Do you have any updates regarding this one instead?

2024-07-23 15:23 UTC, synapticarbors commented
Same comment as on #108. If you are compiling code, it can't be `noarch: python`. That needs to be removed and the PR needs to be re-rendered.

2024-07-23 15:24 UTC, ackphill commented
@flferretti @synapticarbors 
The wandb team is planning to change the backend of wandb from pure python to wandb-core starting with version v0.18.0. As part of this plan, versions v0.17.x include wandb-core, allowing users to explicitly choose to use wandb-core as the backend. However, because wandb-core is compiled using gcc and go, it is dependent on the architecture. As a result, wandb no longer satisfies the noarch requirement. Therefore, I was considering the following options and consequently, updates have been paused:

Merge while maintaining the noarch status, but include a warning that wandb-core is only usable on Linux.
Execute option 1 first, and then propose adding builds for frequently used architectures, removing the noarch status and uploading for each specific architecture.
Just upload the Linux version.

2024-07-23 15:25 UTC, synapticarbors commented
I'm not willing to merge any commits that have the `noarch: python` tag, but are using compilers.

2024-07-23 15:29 UTC, flferretti commented
@synapticarbors tag removed and rerendered. Ready for review, thanks!

2024-07-23 18:20 UTC, flferretti commented
Since W&B requires Swift>3.9, which comes with XCode>15 and therefore MacOSX_SDK>14, and since the SDK is not supported by conda forge, I set `WANDB_BUILD_SKIP_APPLE=true` to make the OSX build pass. This implies that _the statistics from OSX will not be logged_

2024-07-23 18:26 UTC, flferretti commented
Ready for review @synapticarbors. Thanks a lot!

2024-07-23 18:36 UTC, ackphill commented
@flferretti I have learned a lot thanks to you. Thank you for your efforts. 👍

2024-07-23 18:53 UTC, synapticarbors commented on recipe/meta.yaml
> +    - go-licenses
I don't have a lot of familiarity with `go`, but there are some other steps to actually use the `go-licenses`. See:
https://conda-forge.org/docs/maintainer/adding_pkgs/#go

2024-07-23 18:53 UTC, synapticarbors commented on recipe/meta.yaml
>      - pathtools
I don't think `pathtools` or `appdirs` is required any more.

2024-07-23 19:51 UTC, flferretti commented
> @flferretti I have learned a lot thanks to you. Thank you for your efforts. 👍

You're very welcome! I'm glad to hear that :smile:

2024-07-23 19:52 UTC, flferretti commented on recipe/meta.yaml
>      - pathtools
Addressed in https://github.com/conda-forge/wandb-feedstock/pull/105/commits/39c3a1ce8eee74b43de30e456ad35a714ae9af91

2024-07-23 19:52 UTC, flferretti commented on recipe/meta.yaml
> +    - go-licenses
You're right! Addressed in https://github.com/conda-forge/wandb-feedstock/pull/105/commits/55eacc1faab1429acf7b6cea76c2170f740b3760

2024-07-23 19:52 UTC, synapticarbors commented
I'm also wondering if it's worth it to put in a `commands` test of something like:

```
- python -c 'import wandb; wandb.require("core")'
```

to make sure the `core` package is working.

2024-07-23 19:53 UTC, flferretti commented
> I'm also wondering if it's worth it to put in a `commands` test of something like:
> 
> ```
> - python -c 'import wandb; wandb.require("core")'
> ```
> 
> to make sure the `core` package is working.

Sure! I'll add that

2024-07-23 21:44 UTC, flferretti commented on recipe/meta.yaml
> +    - go-licenses
I fear that this might not work as `go-licenses` is not able to find the lincenses associated to the imported packages:

<details><summary>Details</summary>
<p>

```sh
E0723 21:39:46.887980    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/cmd/wandb-core: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
E0723 21:39:46.897946    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/internal/processlib: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/internal/processlib" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
E0723 21:39:46.906443    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/internal/sentry: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/internal/sentry" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
E0723 21:39:46.906485    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go
E0723 21:39:46.906511    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/debug: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/debug
E0723 21:39:46.906529    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/otel/baggage: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/otel/baggage
E0723 21:39:46.906541    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/otel/baggage/internal/baggage: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/otel/baggage/internal/baggage
E0723 21:39:46.906557    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/ratelimit: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/ratelimit
E0723 21:39:46.906572    4379 library.go:122] Failed to find license for golang.org/x/text/cases: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/cases
E0723 21:39:46.906593    4379 library.go:122] Failed to find license for golang.org/x/text/internal: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal
E0723 21:39:46.906609    4379 library.go:122] Failed to find license for golang.org/x/text/language: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/language
E0723 21:39:46.906627    4379 library.go:122] Failed to find license for golang.org/x/text/internal/language: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal/language
E0723 21:39:46.906642    4379 library.go:122] Failed to find license for golang.org/x/text/internal/tag: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal/tag
E0723 21:39:46.906658    4379 library.go:122] Failed to find license for golang.org/x/text/internal/language/compact: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal/language/compact
E0723 21:39:46.906689    4379 library.go:122] Failed to find license for golang.org/x/text/transform: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/transform
E0723 21:39:46.906710    4379 library.go:122] Failed to find license for golang.org/x/text/unicode/norm: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/unicode/norm
E0723 21:39:46.906735    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/traceparser: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/traceparser
E0723 21:39:46.906754    4379 library.go:122] Failed to find license for golang.org/x/sys/execabs: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/sys/execabs
E0723 21:39:46.906783    4379 library.go:122] Failed to find license for github.com/hashicorp/golang-lru: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/hashicorp/golang-lru
E0723 21:39:46.906802    4379 library.go:122] Failed to find license for github.com/hashicorp/golang-lru/simplelru: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/hashicorp/golang-lru/simplelru
E0723 21:39:46.916280    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/internal/version: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/internal/version" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
E0 [...]

2024-07-23 21:47 UTC, synapticarbors commented on recipe/meta.yaml
> +    - go-licenses
Ok, I guess it's fine to drop that.

2024-07-23 21:59 UTC, flferretti commented on recipe/meta.yaml
> +    - go-licenses
Alright, thanks! Finally ready for review then

2024-07-23 23:15 UTC, synapticarbors commented on recipe/meta.yaml
> +    - python
I don't think `python` should be under `requires` as it is just part of the run environment that's automatically there in the tests.

2024-07-23 23:15 UTC, synapticarbors commented on recipe/meta.yaml
> +    - python -c 'import wandb; wandb.require("core")'
I think if you invert the double/single quotes it should work on both linux and windows:

```
python -c "import wandb; wandb.require('core')"
```

2024-07-24 07:10 UTC, flferretti commented on recipe/meta.yaml
> +    - python -c 'import wandb; wandb.require("core")'
Yes, thanks! Addressed in https://github.com/conda-forge/wandb-feedstock/pull/105/commits/6a55dfd6817736d62823aa4c7ee000dfa6b2583b

2024-07-24 07:10 UTC, flferretti commented on recipe/meta.yaml
> +    - python
Addressed in https://github.com/conda-forge/wandb-feedstock/pull/105/commits/6a55dfd6817736d62823aa4c7ee000dfa6b2583b

2024-07-24 08:33 UTC, xhochy requested changes
Please include the go-licenses. If it doesn't work, please paste the error as a comment here.

2024-07-24 08:33 UTC, xhochy commented on recipe/meta.yaml
> +    - {{ compiler('go') }}
```suggestion
    - {{ compiler('go-nocgo') }}
```

2024-07-24 08:33 UTC, xhochy commented on recipe/meta.yaml
> +  script_env: WANDB_BUILD_SKIP_APPLE=true  # [osx]
You could use the 14.3 SDK

2024-07-24 08:39 UTC, h-vetinari commented on recipe/meta.yaml
> +  script_env: WANDB_BUILD_SKIP_APPLE=true  # [osx]
The highest we currently support is 13.3, see [here](https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/1e01340faa89a49c2cf787e38836a9213c980f81/recipe/download_osx_sdk.sh#L40)

2024-07-24 08:47 UTC, flferretti commented
> Please include the go-licenses. If it doesn't work, please paste the error as a comment here.

From https://github.com/conda-forge/wandb-feedstock/pull/105#discussion_r1688762699:

> `go-licenses` is not able to find the lincenses associated to the imported packages:
> 
> <details><summary>Details</summary>
> <p>
> 
> ```sh
> E0723 21:39:46.887980    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/cmd/wandb-core: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
> E0723 21:39:46.897946    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/internal/processlib: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/internal/processlib" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
> E0723 21:39:46.906443    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/internal/sentry: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/internal/sentry" whose name matches regexp ^(?i)((UN)?LICEN(S|C)E|COPYING|README|NOTICE).*$ and locates up until "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core"
> E0723 21:39:46.906485    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go
> E0723 21:39:46.906511    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/debug: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/debug
> E0723 21:39:46.906529    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/otel/baggage: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/otel/baggage
> E0723 21:39:46.906541    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/otel/baggage/internal/baggage: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/otel/baggage/internal/baggage
> E0723 21:39:46.906557    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/ratelimit: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/ratelimit
> E0723 21:39:46.906572    4379 library.go:122] Failed to find license for golang.org/x/text/cases: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/cases
> E0723 21:39:46.906593    4379 library.go:122] Failed to find license for golang.org/x/text/internal: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal
> E0723 21:39:46.906609    4379 library.go:122] Failed to find license for golang.org/x/text/language: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/language
> E0723 21:39:46.906627    4379 library.go:122] Failed to find license for golang.org/x/text/internal/language: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal/language
> E0723 21:39:46.906642    4379 library.go:122] Failed to find license for golang.org/x/text/internal/tag: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal/tag
> E0723 21:39:46.906658    4379 library.go:122] Failed to find license for golang.org/x/text/internal/language/compact: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/internal/language/compact
> E0723 21:39:46.906689    4379 library.go:122] Failed to find license for golang.org/x/text/transform: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/transform
> E0723 21:39:46.906710    4379 library.go:122] Failed to find license for golang.org/x/text/unicode/norm: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/text/unicode/norm
> E0723 21:39:46.906735    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go/internal/traceparser: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go/internal/traceparser
> E0723 21:39:46.906754    4379 library.go:122] Failed to find license for golang.org/x/sys/execabs: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/golang.org/x/sys/execabs
> E0723 21:39:46.906783    4379 library.go:122] Failed to find license for github.com/hashicorp/golang-lru: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/hashicorp/golang-lru
> E0723 21:39:46.906802    4379 library.go:122] Failed to find license for github.com/hashicorp/golang-lru/simplelru: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/hashicorp/golang-lru/simplelru
> E0723 21:39:46.916280    4379 library.go:122] Failed to find license for github.com/wandb/wandb/core/internal/version: cannot find a known open source license for "/home/conda/feedstock_root/build_artifacts/wandb_1721770681665 [...]

2024-07-24 08:52 UTC, flferretti commented on recipe/meta.yaml
> +    - {{ compiler('go') }}
Thanks! Addressed in https://github.com/conda-forge/wandb-feedstock/pull/105/commits/0a2c122154019f99ef42e6746f657d1b08cade7d

2024-07-26 18:07 UTC, flferretti commented
@conda-forge-admin, please rerender

2024-07-26 20:07 UTC, ackphill commented
F.Y.I.
I found a way to bump up the macOS SDK version and apply it to PR #108

2024-07-31 10:21 UTC, synapticarbors commented
How was the `MACOS_SDK_VERSION` chosen? I'm trying to determine what impact this will have since it's a very new version of macos. I'm having trouble finding documentation of the impact. 

Additionally, I'm debating whether we should have a clean PR for either this or 0.17.4 since so much experimentation was done to get everything passing, just so it doesn't make the git history confusing.

2024-07-31 10:34 UTC, flferretti commented
> How was the `MACOS_SDK_VERSION` chosen? I'm trying to determine what impact this will have since it's a very new version of macos. I'm having trouble finding documentation of the impact.

Please check https://github.com/conda-forge/wandb-feedstock/pull/105#issuecomment-2245945068.

2024-07-31 10:50 UTC, flferretti commented
> Additionally, I'm debating whether we should have a clean PR for either this or 0.17.4 since so much experimentation was done to get everything passing, just so it doesn't make the git history confusing.

Please let @ackphill and me know, so we can eventually open a separate PR

2024-07-31 10:54 UTC, synapticarbors commented
@conda-forge/core -- I want to get feedback on whether we think it's ok to set the `MACOSX_SDK_VERSION` to 14.2 here. It's a very new release (December 2023), and my understanding from looking at the docs is that this will potentially limit this packages use to users with 14.2 or newer. There does seem to be an escape hatch to get this built without doing this using an env flag of `WANDB_BUILD_SKIP_APPLE` (https://github.com/wandb/wandb/blob/87b3a46fc4eb70f63889913603f8a11514f6f423/apple_stats/hatch.py#L50-L58). This would skip building the part of wandb that collects systems metrics on apple systems. This might be important to users, so it's a tradeoff. Feedback would be appreciated.

2024-07-31 11:30 UTC, h-vetinari commented
The SDK is not the limiting factor for compatibility (`MACOSX_DEPLOYMENT_TARGET` / `c_stdlib_version` would be), so in general it shouldn't be an issue to bump it. However, what's more problematically IMO is how the upstream build [invokes](https://github.com/wandb/wandb/blob/v0.17.3/apple_stats/hatch.py#L33-L40) directly, circumventing our compiler setup.

I'm not aware of any swift compiled code in conda-forge so far (and I just looked around and couldn't find any), which is arguably a hole in our compiler landscape, but this also means that just calling something that ships in the azure image will potentially create broken packages, if we don't understand the situation around library & runtime ABI there.

Other core members might have a better understanding of this aspect (I could be wrong), but while it's a pity to disable system metrics in a package whose core mission is "A tool for visualizing and tracking your machine learning experiments", I think this might be the safest approach for now. The alternative might take a lot longer (if we have to figure out a new compiler stack).

2024-07-31 11:32 UTC, ackphill commented
@synapticarbors We changed MACOS_SDK_VERSION but did not change MACOSX_DEPLOYMENT_TARGET. It is still [10.13](https://github.com/conda-forge/wandb-feedstock/pull/105/files#diff-79355aefba3d1b6663810e852d1b9b3114abb89df4f97f3770ecdc2ce92aa27f) which is default version of conda-forge.
So I think it's okay to use 14.2 SDK.

About clean PR, I fully agree with creating a new clean PR, and I am willing to cooperate at any time to create a new PR if the current changes are acceptable.

2024-07-31 11:35 UTC, ackphill commented
I think h-vetinari's argument is more accurate than mine.

2024-08-12 08:50 UTC, flferretti commented
> Additionally, I'm debating whether we should have a clean PR for either this or 0.17.4 since so much experimentation was done to get everything passing, just so it doesn't make the git history confusing.

@synapticarbors @conda-forge/wandb do you perhaps have any update on this so we can finally get an updated version of `wandb` on conda-forge?

2024-08-12 11:10 UTC, synapticarbors commented
Reviewing all of the comments, I think there are 3 remaining items:
- Issue with the go licenses -- @xhochy asked for what the errors were, but I'm not sure what the next step is there
- @h-vetinari wants the swift build stuff disabled
- Clean PR so we can keep the `main` branch` uncluttered by all of the experiments

2024-08-12 13:53 UTC, xhochy commented
> Reviewing all of the comments, I think there are 3 remaining items:
> 
> * Issue with the go licenses -- @xhochy asked for what the errors were, but I'm not sure what the next step is there

Please post an output of `go-licenses` and I can then help from there on.

2024-08-12 14:00 UTC, flferretti commented
> > Reviewing all of the comments, I think there are 3 remaining items:
> > 
> > * Issue with the go licenses -- @xhochy asked for what the errors were, but I'm not sure what the next step is there
> 
> Please post an output of `go-licenses` and I can then help from there on.

https://github.com/conda-forge/wandb-feedstock/pull/105#issuecomment-2247257294

2024-08-13 08:07 UTC, flferretti commented
> * @h-vetinari wants the swift build stuff disabled
> 
> * Clean PR so we can keep the `main` branch` uncluttered by all of the experiments

Done in https://github.com/conda-forge/wandb-feedstock/pull/113

> Issue with the go licenses -- @xhochy asked for what the errors were, but I'm not sure what the next step is there

We can continue the discussion on the new PR, so we avoid cluttering this thread

2024-08-28 21:15 UTC, timoffex commented
Now that #113 is merged, what are the next steps here? The changes look good to me, but I'm fairly new to conda.

I'm trying to understand what's happening with `go-licenses`. It seems that conda expects a license in https://github.com/wandb/wandb/tree/main/core/cmd/wandb-core, but this is meant to be covered by https://github.com/wandb/wandb/tree/main/LICENSE. There are many messages like

> E0723 21:39:46.906485    4379 library.go:122] Failed to find license for github.com/getsentry/sentry-go: licenses.Find: rootDir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/cmd/wandb-core should contain dir /home/conda/feedstock_root/build_artifacts/wandb_1721770681665/work/core/vendor/github.com/getsentry/sentry-go

which make me think `core/cmd/wandb-core/` is being treated as the package root. If I understand correctly, this should be `core/`.

2024-09-04 15:13 UTC, flferretti commented
What could be done to solve the issue, is:

```sh
cd core && copy ../LICENSE . && go-licenses save . --save_path="./license-files/"
```

This worked with no errors, but I'm not sure if it's correct

2024-09-04 15:16 UTC, xhochy commented
As this is no a non-noarch package anymore, I suggest that you also add aarch and ppc64le builds, esp. for osx-arm64 via the following lines in `conda-forge.yml`

```
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
```

And then rerender

2024-09-04 15:31 UTC, xhochy commented on recipe/meta.yaml
> +    - go-licenses
```suggestion
    - {{ compiler('go-nocgo') }}
    - go-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
```

2024-09-04 15:45 UTC, xhochy commented on recipe/meta.yaml
> +    - {{ compiler('go-nocgo') }}
The code contains CGO dependencies. I'm confused why it doesn't fail on `linux-64` 🤔 
```suggestion
    - {{ compiler('go-cgo') }}
```

2024-09-04 18:15 UTC, timoffex commented
> What could be done to solve the issue, is:
> 
> ```shell
> cd core && copy ../LICENSE . && go-licenses save . --save_path="./license-files/"
> ```
> 
> This worked with no errors, but I'm not sure if it's correct. Please check [a566e0a](https://github.com/conda-forge/wandb-feedstock/commit/a566e0acec8cae14563119920ee2ed172abdf884)

That's correct---the LICENSE file outside of core/ is the one that applies.

2024-09-04 18:19 UTC, xhochy commented
In `conda-forge.yml`:

```
test: native
```

And append in `recipe/conda_build_config.yaml`:

```
c_stdlib_version:  # [osx and x86_64]
  - "10.15"  # [osx and x86_64]
```

2024-09-05 07:45 UTC, flferretti commented
Thanks a lot for your precious help @xhochy!

2024-09-10 13:07 UTC, flferretti commented
@synapticarbors @xhochy friendly ping :) Thanks a lot!

2024-09-16 13:26 UTC, flferretti commented
@conda-forge/wandb @conda-forge/core could you please handle this? Thanks a lot!

2024-09-16 19:32 UTC, timoffex commented
Thanks @flferretti!

2024-09-16 19:32 UTC, timoffex approved these changes

2024-09-16 19:33 UTC, merged